### ISSUE TITLE
`dbt.cli` uses deprecated `runner` instead of `taskRunner`

### ISSUE THREAD

**Issue by wrussell1999** [kestra-io/plugin-dbt#117] opened 2024-06-07 16:37 UTC
### Expected Behavior

Should use `taskRunner` and `containerImage` to be consistent between plugins.

```yaml
- id: dbt-build
  type: io.kestra.plugin.dbt.cli.Build
  taskRunner:
    type: io.kestra.plugin.scripts.runner.docker.Docker
  dbtPath: /usr/local/bin/dbt
  containerImage: ghcr.io/kestra-io/dbt-bigquery:latest
  inputFiles:
    .profile/profiles.yml: |
      jaffle_shop:
        outputs:
          dev:
            type: bigquery
            dataset: your_big_query_dataset_name
            project: your_big_query_project
            fixed_retries: 1
            keyfile: sa.json
            location: EU
            method: service-account
```

### Actual Behaviour

```yaml
- id: dbt-build
  type: io.kestra.plugin.dbt.cli.Build
  runner: DOCKER
  dbtPath: /usr/local/bin/dbt
  docker:
    image: ghcr.io/kestra-io/dbt-bigquery:latest
  inputFiles:
    .profile/profiles.yml: |
      jaffle_shop:
        outputs:
          dev:
            type: bigquery
            dataset: your_big_query_dataset_name
            project: your_big_query_project
            fixed_retries: 1
            keyfile: sa.json
            location: EU
            method: service-account
```

Related:
https://github.com/kestra-io/plugin-dbt/blob/474ce236b3669588b713d07792a8dad60dc1fd35/src/main/java/io/kestra/plugin/dbt/cli/AbstractDbt.java#L82-L93

### Environment Information

- Kestra Version: 0.18 Snapshot
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by anna-geller** [comment] 2024-06-08 11:16
it's not a bug, we plan to add task runner support for CLI tasks in 0.18, it's part of https://www.notion.so/kestra-io/Task-Runners-c03ab232623f4ed0b71ac792e246aeeb?pvs=4 but well spotted that it's not added yet 👍

**Comment by loicmathieu** [comment] 2024-06-10 08:17
And as far as I know the `runner` is not deprecated.

I'm going to close this one as I'll open a single issue to track all tasks and plugins that needs to integrate with task runners.

**Closed by loicmathieu** 2024-06-10 08:17 UTC
Labels: enhancement
