### ISSUE TITLE
Task crash when DBT Cloud job returns "No nodes selected!"

### ISSUE THREAD

**Issue by aballiet** [kestra-io/plugin-dbt#105] opened 2024-04-11 15:54 UTC
### Expected Behavior

Task should parse successfully status of the job as Success from dbt Cloud

### Actual Behaviour

Fails with following logs : 
<img width="1016" alt="image" src="https://github.com/kestra-io/plugin-dbt/assets/25565600/6b4e0d1c-5730-474e-9ed3-5aab2bc79e16">

### Steps To Reproduce

Create a dbt job which will not run any models as there is no selection, case when running `dbt list --select state:modified+` for example and no model has been modified

### Environment Information

- Kestra Version: 0.15.10
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): K8s
- Java Version (If not docker):

**Comment by aballiet** [comment] 2024-04-11 15:56
I am willing to provide a PR 👍

**Comment by anna-geller** [comment] 2024-04-25 10:27
PR is welcome 🙏

**Comment by anna-geller** [comment] 2024-05-06 10:08
@aballiet are you working on a PR?

**Comment by anna-geller** [comment] 2024-09-15 19:07
@Ben8t can you reproduce and see if the issue persists? if yes, would be cool to prioritize with with Matt (as discussed together, dbt is one of the top plugins we want to improve)

**Comment by Ben8t** [comment] 2024-09-17 08:18
@aballiet I'm not able to reproduce, I can get dbt to fails finding nodes (see screenshot below) but no error anymore 🤔 
![image](https://github.com/user-attachments/assets/c33ae8e4-bb49-4de1-b2fb-65190989e78f)

I'm closing, don't hesitate to reopen if you still face the issue

**Closed by Ben8t** 2024-09-17 08:18 UTC
Labels: bug, area/plugin

**Comment by aballiet** [comment] 2024-09-17 08:43
Yes perfect, sorry for delay
